### ISSUE TITLE
Title screen and cross-fades are extremely slow in VD2

### ISSUE THREAD

**Issue by Kupo91** [libretro/easyrpg-libretro#21] opened 2018-10-14 20:36 UTC

**Comment by Ghabry** [comment] 2018-11-19 23:28
Do you know if your system has hardware acceleration?

**Comment by Kupo91** [comment] 2018-11-20 00:48
Hm no clue. But thats what my retroarch system information shows maybe it helps?

![20181010_030250](https://user-images.githubusercontent.com/41426906/48744048-f7ea9c80-ec65-11e8-9428-6139a3a8e9d6.jpg)
![20181010_030320](https://user-images.githubusercontent.com/41426906/48744054-ff11aa80-ec65-11e8-98ad-ff33c3b8f0b8.jpg)
![20181010_030359](https://user-images.githubusercontent.com/41426906/48744063-05a02200-ec66-11e8-8d52-8d3d623497b9.jpg)
![20181010_030446](https://user-images.githubusercontent.com/41426906/48744072-0b960300-ec66-11e8-86de-36f1230f0a0d.jpg)
![20181010_030515](https://user-images.githubusercontent.com/41426906/48744077-12bd1100-ec66-11e8-99e2-34682e7801a4.jpg)
![20181010_030538](https://user-images.githubusercontent.com/41426906/48744084-18b2f200-ec66-11e8-9cf7-3a9b4473b71c.jpg)

**Comment by Ghabry** [comment] 2018-11-20 11:20
well I see OpenGL ES so this shouldn't be the problem.

**Comment by Ghabry** [comment] 2018-11-21 02:36
guess this is more or less a dupe of #22 
hopefully resolved with frameskipping and neon...

**Closed as completed by Ghabry** 2018-11-21 02:36 UTC

**Comment by Kupo91** [comment] 2018-11-21 16:01
Yes it seems to be gone now. Thanks a lot
