### ISSUE TITLE
Crash when closing core on Android

### ISSUE THREAD

**Issue by spielvan** [libretro/easyrpg-libretro#36] opened 2019-01-13 15:16 UTC
Hello, my dear, congratulations on the great design, this is practically complete with everything working, I remember that we were talking about Ini problems, accents, Wads, now everything working a wonder, the only bug I noticed was when it leaves the core of easy rpg that closes the retroarch , otherwise this is perfect, congratulations for the great work, and a great 2019.

**Comment by Ghabry** [comment] 2019-01-13 15:21
Well, figuring out these shutdown crashes is very annoying (and only happens on Android), therefore: Patches welcome, won't look at this very soon.

**Comment by Ghabry** [comment] 2019-04-16 22:26
@spielvan 
I rewrote the whole init and shutdown code.
Please retest when the core is rebuilt (can take a day).
The core version should be cd707dc

**Comment by spielvan** [comment] 2019-04-17 17:57
> @spielvan
> I rewrote the whole init and shutdown code.
> Please retest when the core is rebuilt (can take a day).
> The core version should be [cd707dc](https://github.com/libretro/easyrpg-libretro/commit/cd707dcc6fc8f012395335cbc1b9c725439d532e)

I tested what came out on 17.04.2019, 14:47 and still continues closing all retroarch, when I click on close core.

**Comment by Ghabry** [comment] 2019-04-18 11:56
Can confirm this behaviour and the stacktrace is useless, so I won't work on a fix for this because figuring this out will take days.
Maybe some RetroArch update will fix it by chance, as all other systems work :/

**Comment by spielvan** [comment] 2019-04-18 16:59
> Can confirm this behaviour and the stacktrace is useless, so I won't work on a fix for this because figuring this out will take days.
> Maybe some RetroArch update will fix it by chance, as all other systems work :/

I suspect that retroarch is a core interfering in the other, in these latter versions, it has other colors that close the retroarch when it clicks close core, I will test here previous versions of retroarch, 1.75, 174 ..., I am thinking that retroarch is including so much in the last versions that left the whole code very heavy and unstable.

**Comment by spielvan** [comment] 2019-04-18 17:01
But the important thing that Easy RPG itself works normal, one thing I remembered is how to slow down the dpad Dead Zone? because he ends up walking very fast, which in the RPG marker gets in the way of the precise movements. A hug.

**Comment by Ghabry** [comment] 2019-04-18 22:15
what do you mean with dpad deadzone? A digital pad only has pressed and not pressed as states.

**Comment by spielvan** [comment] 2019-04-19 16:10
> what do you mean with dpad deadzone? A digital pad only has pressed and not pressed as states.

The dead zone would be the zone that the character walks, with the touch on the directional, type the sensitivity of the mouse, for more precise movements a low sensitivity, for faster movements a high sensitivity. I was playing the RPG Marker game "Rigar and the Soldiers of the King" has part that has platforms that need to get well on the tip of the same to jump, something like that and if the movement is not very precise, ends up not being able to execute in those parts .

**Comment by Ghabry** [comment] 2019-04-26 22:47
@spielvan 
Could you download the latest core from the core downloader?

I think I found a workaround, is the same bug as on Windows...

**Comment by spielvan** [comment] 2019-04-26 23:14
> @spielvan
> Could you download the latest core from the core downloader?
> 
> I think I found a workaround, is the same bug as on Windows...

Can I download yes, is it already available? or down tomorrow, this problem also occurs with other colors type the latest builds of parallel64, atari800 .. I do not know the reason when you click to close the core closes the retroarch.

**Comment by Ghabry** [comment] 2019-04-26 23:16
yes, I tested the core already @spielvan

**Comment by Ghabry** [comment] 2019-04-26 23:24
No idea what the problem for parallel and atari is, for EasyRPG the problem is that I use the Audio callback API (only 3 cores use this one) which makes Audio run independent of the game in another thread and RetroArch somehow calls the callbacks again when the core was already unloaded -> crash.

That's obviously a RetroArch bug, I workaround it by disabling the audio callbacks now when shutting down.
parallel and atari don't use this function but it's still possible that the bug is similiar but with other callbacks.

**Comment by spielvan** [comment] 2019-04-27 00:24
> No idea what the problem for parallel and atari is, for EasyRPG the problem is that I use the Audio callback API (only 3 cores use this one) which makes Audio run independent of the game in another thread and RetroArch somehow calls the callbacks again when the core was already unloaded -> crash.
> 
> That's obviously a RetroArch bug, I workaround it by disabling the audio callbacks now when shutting down.
> parallel and atari don't use this function but it's still possible that the bug is similiar but with other callbacks.

Now it's working perfectly, congratulations, man, there's only two things left, an option to use cheats and a way for dpad not to walk so fast, to be able to make short and precise movements. A big hug

**Comment by Ghabry** [comment] 2019-04-27 00:41
Cheats through the libretro API make no sense because this is not an emulator, the memory layout is different.
You can enable the debug mode in the core options and map it to the RetroPad.

Can you send me a game that is unplayable with the current way the dpad works? I have no issues doing single-tile moves.

**Closed as completed by Ghabry** 2019-04-27 00:41 UTC
Labels: bug, help wanted

**Comment by spielvan** [comment] 2019-04-27 01:36
Rygar 1: And the soldiers of the King


Rygar 2: Against the Empire of Evil


Rygar 3: Rygar in the Lost Kingdom
