### ISSUE TITLE
Red -1252 error screen, in the last builds

### ISSUE THREAD

**Issue by spielvan** [libretro/easyrpg-libretro#33] opened 2018-12-03 19:01 UTC
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Name of the game:
Rygar e os soldados do rei

#### Player platform:
Windows, Linux, Android, ...
Android

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:
Red -1252 error screen, in the last builds

[https://4.bp.blogspot.com/-GyIeSa3XOqY/XAV9RzbwPuI/AAAAAAAADT4/I13NRRs7sVowVaXNz0GZXYVtN-pcHCmUwCLcBGAs/s1600/f523f082-81d8-4c90-a6d2-202b353ce0cf.jpg](https://4.bp.blogspot.com/-GyIeSa3XOqY/XAV9RzbwPuI/AAAAAAAADT4/I13NRRs7sVowVaXNz0GZXYVtN-pcHCmUwCLcBGAs/s1600/f523f082-81d8-4c90-a6d2-202b353ce0cf.jpg)

**Comment by Ghabry** [comment] 2018-12-03 20:31
hmpf, this happens on multiple platforms... going to recompile this with a different ICU data file :/

**Comment by Ghabry** [comment] 2018-12-05 12:41
Fixed but now it suddenly crashes for me when closing the game... This worked a few days ago when I tested it. RetroArch is such an unstable mess.

**Closed as completed by Ghabry** 2018-12-05 12:41 UTC
Labels: bug

**Comment by spielvan** [comment] 2018-12-05 13:14
@Ghabry I will update here and test in the android box, this to close the core, when exiting a game occurs also in the core parallel64, and in his case is still worse because as it ends the retroarch, you can not change the core settings, I I have the impretion that many colors are not tested mano, type the FCEUMM it had a problem with the Arkanoid of nes, did not work the dpad, since 2016 all the versions had this problem, then last month I reported the problem in the github of the programmer and in 5 minutes he packed, sometimes lacking tests in many colors unhappily. I always find that bug in the tests I will report, because the retroarch is all of us the steady it gets better. Always a hug and success.

**Comment by spielvan** [comment] 2018-12-05 13:36
I tested it here and it worked, I only found 2 bugs, one that as soon as it loads the game appears a sentence in yellow in the upper part solo after passing the screen soon of EASYRPG, asking for the installation RTP, it could be because I changed that line to hit the accents of the sentences and the second bug was to close the core when it leaves the game or try to load another game with the core open, the reset option works normally, the sound part, accent and game pad working perfectly, hand the core is practically perfect, congratulations for the great work, who knows someday, we do not also have mugen and openbor as retroarch colors.

**Comment by Ghabry** [comment] 2018-12-05 14:23
the RTP thing is not a bug, you have to manually install this. It is a shared asset collection used by many 2k and 2k3 games.

It can't be provided via the content downloader because that violates the RTP license.

It belongs in RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY/rtp/2000 (or 2003). No idea where that path is on Android or anywhere else, sorry.

**Comment by spielvan** [comment] 2018-12-05 15:03
Strange to give this message mano, as I have in the games that I tested the RTP built in the game, including I load the game in Easyrpg through the RTP.INI.

**Comment by Ghabry** [comment] 2018-12-05 16:22
That Message is generic, the Player doesn't check if the game has any RTP resources bundled

**Comment by spielvan** [comment] 2018-12-05 17:02
and I could not leave this message hidden, like an option to mark in the core of easyrpg, to hide this message, type what has in the core of the mame, not to show the warning part in loading the game.

**Comment by Ghabry** [comment] 2018-12-05 20:20
You can mark a game as RTP free by providing FullPackageFlag=1 in the RPGRT section of the INI.

**Comment by spielvan** [comment] 2018-12-06 00:29
I put this code and it was perfect, thanks man, any idea to add cheats to the project? and another thing was playing Rygar and the King's soldiers, and there is a platform part that he needs to turn around but when he presses the gamepad to the right for him to turn he walks and falls off the platform, it would be an option for him to turn the character , without having to move.

**Comment by Ghabry** [comment] 2018-12-06 01:08
There is a debug mode which you can use for cheating. I plan to expose this and a few other things as a core option later. 

Could you provide a savegame (*.lsd file, upload as zip) close to that problem? THat sounds like a bug.

**Comment by spielvan** [comment] 2018-12-06 12:53
This cheats would taste like mano, nothing bug, the project is beautiful now, and I can tell you after tests that this better the separate Easyplayer, using in the box android with a ps2 control converted to xbox 360 control, only the The only thing to think about is the dead zone of dpad, it would have to have a way of letting the movements shorter, in the normal gameplay goes perfect, but in rpg with precise platforms, it ends up difficult, I have the Kade mini console + and the Retropad 32 with them I can connect control of snes, mega drive ... in practically every video game, I will test the easyrpg core with snes control to see how dpad is. A big hug

**Comment by Ghabry** [comment] 2018-12-06 13:07
A dpad has no dead zone, a dpad has only pressed or not pressed.

Anyway this is one of the reasons to prefer the core over the standalone: You get special features provided by RetroArch which will never or not very soon land in the standalone Player because of lack of developers and motivation (we don't implement stuff we don't use ^^)
